### ISSUE TITLE
Dependency on yq should appear in README

### ISSUE THREAD

**Issue by amacleod** [Townk/zmk-cli#1]
Trying to do `zmk build all` after copying the bin contents to `~/.local/bin`, I got the following error:
```
/home/amacleod/.local/bin/_zmk_lib.sh: line 137: yq: command not found
```

I was able to install it with `snap install yq`, but it was not installed by default on my Ubuntu system.

Mentioning in the readme that the scripts depend on yq should hopefully help others in a similar situation.

**Comment by Townk** [comment]
Thank you for this issue. I pushed a [commit](https://github.com/Townk/zmk-cli/commit/8d1cce145e88b256d4c267a89716843c20275ade) that fixes that, and, hopefully, prevents the issue from ever happening. If `yq` is not installed, the script will try to download the portable binary to the same directory as the CLI scripts.

Get the latest changes and let me know what you think. Also, feel free to open any issue with requirements or issues you find using the tool.

**Comment by amacleod** [comment]
I will give it a try next time I am on my Ubuntu machine
